project:
  type: website
  output-dir: docs

website:
  title: "SACoLib"
  navbar:
    right:
      - href: index.qmd
      - Animal Liberation.qmd
      - Information Liberation.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

